baseURL = 'https://example.org/'
title = 'Gix Theme'
theme = "gix-theme"
timeZone = "Asia/Makassar"
# for auto last mod
enableGitInfo = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[mediaTypes]
[mediaTypes."text/plain"]
suffixes = ["txt"]

[outputFormats]
[outputFormats.RobotsTxt]
baseName = "robots"
isPlainText = true
mediaType = "text/plain"

[languages]
# English
[languages.en]
languageCode = 'en-us'
languageName = "English"
weight = 1
contentDir = "content/en"
# create robots.txt only on root 
outputs.home = ["HTML", "RSS", "RobotsTxt"]

[[languages.en.menu.main]]
name = 'Apps'
pageRef = '/apps'
weight = 1
[[languages.en.menu.main]]
name = 'Blog'
pageRef = '/posts'
weight = 2
[[languages.en.menu.main]]
name = 'About'
pageRef = '/about'
weight = 3

[[languages.en.menu.secondary]]
name = 'Home'
pageRef = '/'
weight = 1
[[languages.en.menu.secondary]]
name = 'Apps'
pageRef = '/apps'
weight = 2
[[languages.en.menu.secondary]]
name = 'Blog'
pageRef = '/posts'
weight = 3
[[languages.en.menu.secondary]]
name = 'About'
pageRef = '/about'
weight = 4

# Indonesia

[languages.id]
languageCode = 'id-ID'
languageName = "Indonesia"
weight = 2
contentDir = "content/id"
[[languages.id.menu.main]]
name = 'Aplikasi'
pageRef = '/apps'
weight = 1
[[languages.id.menu.main]]
name = 'Blog'
pageRef = '/posts'
weight = 2
[[languages.id.menu.main]]
name = 'Tentang'
pageRef = '/about'
weight = 3

[[languages.id.menu.secondary]]
name = 'Beranda'
pageRef = '/'
weight = 1
[[languages.id.menu.secondary]]
name = 'Aplikasi'
pageRef = '/apps'
weight = 2
[[languages.id.menu.secondary]]
name = 'Blog'
pageRef = '/posts'
weight = 3
[[languages.id.menu.secondary]]
name = 'Tentang'
pageRef = '/about'
weight = 4

[params.pagination]
# Number of items for term pages (e.g., /tags/blue/)
termPaginate = 15
sectionPaginate = 3

[params.BlogSettings]
logo = "/logo/logo-gihex.png"
footerTitle = "GixTheme.com"

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
