baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Gix Theme'
theme = "gix-theme"

[params.pagination]
# Number of items for term pages (e.g., /tags/blue/)
termPaginate = 15
sectionPaginate = 3

[params.BlogSettings]
logo = "/logo/logo-gihex.png"
footerTitle = "GixTheme.com"


# kind of content
[[params.BlogContentKinds]]
name = "Posts"
maxShow = 5
section = "posts"
url = "/posts"
defaultThumbnail = "/images/def_th.png"


[[params.BlogContentKinds]]
name = "Apps"
maxShow = 6
section = "apps"
url = "/apps"
defaultThumbnail = "/images/def_th.png"


# menu navbar
[menus]

[[menus.main]]
name = 'Apps'
pageRef = '/Apps'
weight = 1

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 2

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 3

[[menus.secondary]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.secondary]]
name = 'Apps'
pageRef = '/Apps'
weight = 2

[[menus.secondary]]
name = 'Blog'
pageRef = '/blog'
weight = 3

[[menus.secondary]]
name = 'About'
pageRef = '/about'
weight = 4
