baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Gix Theme'
theme = "gix-theme"

[params.BlogSettings]
logo = "/logo/logo-gihex.png"
footerTitle = "GixTheme.com"

# kind of content
[[params.BlogContentKinds]]
name = "Posts"
maxShow = 2
section = "posts"
url = "/posts"
defaultThumbnail = "/logo/logo-gihex.png"


[[params.BlogContentKinds]]
name = "News"
maxShow = 6
section = "news"
url = "/news"
defaultThumbnail = "/logo/logo-gihex.png"


# menu navbar
[menus]

[[menus.main]]
name = 'Apps'
pageRef = '/Apps'
weight = 1

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 2

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 3

[[menus.secondary]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.secondary]]
name = 'Apps'
pageRef = '/Apps'
weight = 2

[[menus.secondary]]
name = 'Blog'
pageRef = '/blog'
weight = 3

[[menus.secondary]]
name = 'About'
pageRef = '/about'
weight = 4
