baseURL = 'https://example.org/'
title = 'Gix Theme'
theme = "gix-theme"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
# English
[languages.en]
languageCode = 'en-us'
languageName = "English"
weight = 1
contentDir = "content/en"
[[languages.en.menu.main]]
name = 'Apps'
pageRef = '/apps'
weight = 1
[[languages.en.menu.main]]
name = 'Blog'
pageRef = '/posts'
weight = 2
[[languages.en.menu.main]]
name = 'About'
pageRef = '/about'
weight = 3

[[languages.en.menu.secondary]]
name = 'Home'
pageRef = '/'
weight = 1
[[languages.en.menu.secondary]]
name = 'Apps'
pageRef = '/apps'
weight = 2
[[languages.en.menu.secondary]]
name = 'Blog'
pageRef = '/posts'
weight = 3
[[languages.en.menu.secondary]]
name = 'About'
pageRef = '/about'
weight = 4

# kind of content
[[languages.en.params.BlogContentKinds]]
name = "Posts"
maxShow = 5
section = "posts"
url = "/posts"
defaultThumbnail = "/images/def_th.png"
[[languages.en.params.BlogContentKinds]]
name = "Apps"
maxShow = 6
section = "apps"
url = "/apps"
defaultThumbnail = "/images/def_th.png"

# Indonesia

[languages.id]
languageCode = 'id'
languageName = "Indonesia"
weight = 2
contentDir = "content/id"
[[languages.id.menu.main]]
name = 'Aplikasi'
pageRef = '/apps'
weight = 1
[[languages.id.menu.main]]
name = 'Blog'
pageRef = '/posts'
weight = 2
[[languages.id.menu.main]]
name = 'Tentang'
pageRef = '/about'
weight = 3

[[languages.id.menu.secondary]]
name = 'Beranda'
pageRef = '/'
weight = 1
[[languages.id.menu.secondary]]
name = 'Aplikasi'
pageRef = '/apps'
weight = 2
[[languages.id.menu.secondary]]
name = 'Blog'
pageRef = '/posts'
weight = 3
[[languages.id.menu.secondary]]
name = 'Tentang'
pageRef = '/about'
weight = 4

# kind of content
[[languages.id.params.BlogContentKinds]]
name = "Postingan"
maxShow = 5
section = "posts"
url = "/id/posts"
defaultThumbnail = "/images/def_th.png"
[[languages.id.params.BlogContentKinds]]
name = "Aplikasi"
maxShow = 6
section = "apps"
url = "/id/apps"
defaultThumbnail = "/images/def_th.png"


[params.pagination]
# Number of items for term pages (e.g., /tags/blue/)
termPaginate = 15
sectionPaginate = 3

[params.BlogSettings]
logo = "/logo/logo-gihex.png"
footerTitle = "GixTheme.com"
