baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[mediaTypes]
[mediaTypes."text/plain"]
suffixes = ["txt"]

[outputFormats]
[outputFormats.RobotsTxt]
baseName = "robots"
isPlainText = true

[outputs]
home = ["html", "rss", "RobotsTxt"]

# taxonomi
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"


# Sets the default number of items per page.
[params.pagination]
# /tags/blue
termPaginate = 15
# /posts
sectionPaginate = 12

[params.BlogSettings]
logo = "/"
footerTitle = "Gix Theme"

[params.Cookies]
cookieConsentTitle = "Your privacy is important to us"
cookieConsentDescription = "We use cookies to ensure you get the best experience on our website. You can choose to accept all cookies or manage your own preferences at configure cookie page."
cookieConfigurePage = "cookie-configure.md"


[[params.CookiesItem]]
cookieKinds = "Cloudflare Web Analytics"
cookieDescription = "Kami menggunakan layanan web analitik dari Cloudflare untuk memahami performa situs dan cara pengunjung berinteraksi dengan konten kami. Untuk keperluan tersebut cookie ini akan selalu aktif."
idCookie = "cf_web_analytics"
isConfigureable = false

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
[module.hugoVersion]
extended = false
min = '0.146.0'
