baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[mediaTypes]
[mediaTypes."text/plain"]
suffixes = ["txt"]

[outputFormats]
[outputFormats.RobotsTxt]
baseName = "robots"
isPlainText = true

[outputs]
home = ["html", "rss", "RobotsTxt"]

# taxonomi
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"


# Sets the default number of items per page.
[params.pagination]
# /tags/blue
termPaginate = 15
# /posts
sectionPaginate = 12

[params.BlogSettings]
logo = "/"
footerTitle = "Gix Theme"


# kind of content
[[params.BlogContentKinds]]
name = "Posts"
maxShow = 2
section = "posts"
url = "/posts"
defaultThumbnail = "/images/bryce-canyon.jpg"

[[params.BlogContentKinds]]
name = "News"
maxShow = 6
section = "news"
url = "/news"
defaultThumbnail = "/images/bryce-canyon.jpg"


[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
[module.hugoVersion]
extended = false
min = '0.146.0'
